### PR TITLE
[V2] fix: Fix verify-examples.sh leak resources created 🐞

### LINKED ISSUE #1288: [V2] verify-examples.sh leaks deployment and stateful set when running e2e tests
**What happened**:
When running e2e tests, `/hack/verify_examples.sh` runs as a part of the `ginkgo.AfterSuite` test hook in `test/e2e/suite_test.go`. This script leaks a deployment and stateful set that can interfere to subsequent test runs that expect a clean system.

**What you expected to happen**:
I expect there to be no deployment or stateful set left over after running an e2e test. 

**How to reproduce it**:
1. Run an e2e test
2. Execute `kubectl get all`
3. Observer that there is a deployment and stateful set in the default namespace after the test run.

**Anything else we need to know?**:
This is part of the testing infrastructure and not related to features or functionality.

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jmclong**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
When running e2e tests interactively, `/hack/verify-examples.sh` runs as a part of the `ginkgo.AfterSuite` test hook in `test/e2e/suite_test.go`. This script leaks a deployment and stateful set that can interfere to subsequent test runs that expect a clean system.

**Which issue(s) this PR fixes**:

Fixes #1288 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: hack/verify-examples.sh [hunk 1]
```diff
@@ -74,8 +74,17 @@ if [[ "$1" == "windows" ]]; then
...
+        echo "Attempting deletion of \"$EXAMPLE\""
+        kubectl delete -f "$EXAMPLE" --ignore-not-found
+    done
+}
+
+trap cleanup_examples EXIT
+
 for EXAMPLE in "${EXAMPLES[@]}"; do
-    rollout_and_wait $EXAMPLE
+    rollout_and_wait "$EXAMPLE"
```
Comment (nearora-msft) [inline hack/verify-examples.sh:87]: Why is this change needed?

Comment (jmclong) [reply hack/verify-examples.sh:87]: If there's a space in $EXAMPLE it will split into multiple args. For example

```bash
#!/usr/bin/env bash

hello_world() {
  echo $1
}
VAR="Hello, world"
hello_world $VAR
hello_world "$VAR"
```
Prints:
```
Hello,
Hello, world!
```

I looked at the context, and it was clear that $EXAMPLE is meant to be a single argument, so I fixed it.

Comment (nearora-msft) [reply hack/verify-examples.sh:87]: Ah ok, thanks for explaining!

**Review by nearora-msft — APPROVED** [review]
