### PR TITLE
fix: Exclude os disks from the ListVolumes response

### LINKED ISSUE #678: ListVolumes should not include OS disks in the response
**What happened**:
Current ListVolumes implementation returns all the disks in a resource group including the os disks

**What you expected to happen**:
The response shouldn't contain OS disks

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #678 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: pkg/azuredisk/controllerserver.go [hunk 1]
```diff
@@ -581,22 +581,25 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
 		d := disks[i]
 		nodeList := []string{}
 
-		if d.ManagedBy != nil {
-			attachedNode, err := vmSet.GetNodeNameByProviderID(*d.ManagedBy)
-			if err != nil {
-				return nil, err
+		// HyperVGeneration property is only setup for os disks. Only the non os disks should be included in the list
+		if !(d.DiskProperties != nil && d.DiskProperties.HyperVGeneration != "") {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:585]: this is more clear:
`d.DiskProperties == nil || d.DiskProperties.HyperVGeneration == ""`

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
