### PR TITLE
fix: resize filesystem if cloned volume capacity is larger than the source volume

### LINKED ISSUE #528: Mounted volume size issue when cloning a larger size pvc
**What happened**:
When cloned a target PVC with a larger size(16G) than the original PVC(8G), the mounted volume size for the container is accurately 8G.

**What you expected to happen**:
When cloned a target PVC with a larger size(16G) than the original PVC(8G), the mounted volume size for the container should equal to 16G

**How to reproduce it**:
Create original pvc(8G)
clone target pvc(16G)
Create pod and consume target pvc

**Anything else we need to know?**:
Some check on the worker:

$ df -h | grep pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8
/dev/sdd                              7.9G  4.5M  7.9G   1% /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8/globalmount

$ lsblk | grep pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8
sdd                            8:48   0    16G  0 disk /var/lib/kubelet/pods/5a8ef385-efe0-4f0d-91b2-0d9bbcd39bbc/volumes/kubernetes.io~csi/pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8/mount

**Environment**:
- CSI Driver version: azuredisk-csi:v0.7.0
- Kubernetes version (use `kubectl version`):  latest happen on 1.19, but seen in 1.18 as well
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sunpa93**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
**Which issue(s) this PR fixes**:

Fixes #528 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: test/e2e/dynamic_provisioning_test.go [hunk 1]
```diff
@@ -382,6 +382,45 @@ func (t *dynamicProvisioningTestSuite) defineTests(isMultiZone bool) {
 		test.Run(cs, ns)
 	})
 
+	ginkgo.It("should clone a volume of larger size than the source volume and make sure the filesystem is appropriately adjusted [disk.csi.azure.com]", func() {
+		skipIfTestingInWindowsCluster()
+		skipIfUsingInTreeVolumePlugin()
+		if !isMultiZone {
+			// todo: remove this when single-az tests are runnong on 1.16
+			ginkgo.Skip("test case not supported by single-az test since it's running on 1.15")
```
Comment (andyzhangx) [inline test/e2e/dynamic_provisioning_test.go:390]: why it's related to 1.15?

File: pkg/azuredisk/controllerserver.go [hunk 2]
```diff
@@ -162,6 +163,7 @@ func (d *Driver) CreateVolume(ctx context.Context, req *csi.CreateVolumeRequest)
 			//return nil, fmt.Errorf("AzureDisk - invalid option %s in storage class", k)
 		}
 	}
+	parameters["resizeRequired"] = strconv.FormatBool(false)
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:166]: make `resizeRequired` as a const

File: pkg/azuredisk/controllerserver.go [hunk 3]
```diff
@@ -839,6 +844,36 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
...
+func (d *Driver) GetSourceDiskSize(resourceGroup, diskName string) (*int32, error) {
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	return d.GetSourceDiskSizeHelper(ctx, resourceGroup, diskName)
+}
+
+// GetSourceDiskSizeHelper is a helper function for GetSourceDiskSize to support recursive search for  and it returns: disk size, error
+func (d *Driver) GetSourceDiskSizeHelper(ctx context.Context, resourceGroup, diskName string) (*int32, error) {
+	result, rerr := d.cloud.DisksClient.Get(ctx, resourceGroup, diskName)
+
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:857]: remove empty line

File: pkg/azuredisk/controllerserver.go [hunk 4]
```diff
@@ -839,6 +844,36 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
...
+	if rerr != nil {
+		return nil, rerr.Error()
+	}
+
+	if result.DiskProperties.CreationData != nil && (*result.DiskProperties.CreationData).CreateOption == "Copy" {
+		klog.V(2).Infof("Clone source disk has a parent source")
+		sourceResourceID := *result.DiskProperties.CreationData.SourceResourceID
+		parentResourceGroup, _ := GetResourceGroupFromURI(sourceResourceID)
+		parentDiskName := path.Base(sourceResourceID)
+		return d.GetSourceDiskSizeHelper(ctx, parentResourceGroup, parentDiskName)
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:867]: if current disk has parent disk, why return parent disk size? should it always return current disk size?

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

File: pkg/azuredisk/nodeserver.go [hunk 5]
```diff
@@ -216,6 +216,22 @@ func (d *Driver) NodePublishVolume(ctx context.Context, req *csi.NodePublishVolu
 	if err := d.mounter.Mount(source, target, "", mountOptions); err != nil {
 		return nil, status.Errorf(codes.Internal, "Could not mount %q at %q: %v", source, target, err)
 	}
+
+	// if resize is required, resize filesystem
+	if resizeRequired, ok := req.GetVolumeContext()["resizeRequired"]; ok && resizeRequired == "true" {
+		klog.V(2).Infof("fs resize initiating.")
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver.go:222]: klog.V(2).Infof("fs resize initiating on target(%s) volumeid(%s)", target, volumeid)

File: pkg/azuredisk/nodeserver.go [hunk 6]
```diff
@@ -216,6 +216,22 @@ func (d *Driver) NodePublishVolume(ctx context.Context, req *csi.NodePublishVolu
...
+		if err != nil {
+			return nil, status.Errorf(codes.Internal, "Could not get volume path for %s: %v", target, err)
+		}
+
+		resizer := resizefs.NewResizeFs(d.mounter)
+		if _, err := resizer.Resize(devicePath, target); err != nil {
+			return nil, status.Errorf(codes.Internal, "Could not resize volume %q (%q):  %v", req.GetVolumeId(), devicePath, err)
+		}
+
+		klog.V(2).Infof("fs resize successful.")
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver.go:233]: klog.V(2).Infof("fs resize succeeded on target(%s) volumeid(%s)", target, volumeid)

File: pkg/azuredisk/controllerserver.go [hunk 7]
```diff
@@ -839,6 +844,36 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
...
+	}
+
+	if result.DiskProperties == nil {
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:870]: Shouldn't this check be placed before the if condition on line 862?

File: pkg/azuredisk/controllerserver.go [hunk 8]
```diff
@@ -273,6 +275,9 @@ func (d *Driver) CreateVolume(ctx context.Context, req *csi.CreateVolumeRequest)
 					},
 				}
 
+				if sourceGiB, _ := d.GetSourceDiskSize(resourceGroup, path.Base(sourceID)); sourceGiB != nil && *sourceGiB < int32(requestGiB) {
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:278]: Would it be better to compare the requestGiB with the size of the newly created disk instead of the source? I am thinking if they change the implementation later to create the target disks with the right requestGib size, then there would be no need to resize.

File: pkg/azuredisk/controllerserver.go (hunk 4 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:867]: It is a safety measure. As I was marking through a few test cases, I observed that if you clone a new target volume from an previously cloned volume that has a parent disk of smaller size, the new target volume's filesystem inherits the parent disk's fs capacity instead of cloned volume's fs capacity.

Without the recursive search, you can replicate the error by:
```
Clone a 16Gi target volume B from a 8Gi volume A.
B's target capacity > A's capacity
     B's filesystem resized in nodeserver
B's filesystem shows 16Gi capacity

Clone a 16Gi target volume C from B
C's target capacity == B's capacity
     C's filesystem not resized
C's filesystem ends up 8Gi for some reason.
```

File: pkg/azuredisk/controllerserver.go (hunk 7 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:870]: You are right. I don't know how that ended up there haha. Thanks for pointing that out.

File: pkg/azuredisk/controllerserver.go (hunk 8 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:278]: The clone volume size problem comes from the target volume's filesystem that is not resized along with the expanded disk size. The new target disk is created with the right requestGib size; it's just that its filesystem also needs to be adjusted to its target size, which nodeserver will later do as it publishes the volume. So in our case, the size of the newly created disk will match requestGiB, which is why we cannot use it for this conditional clause.

File: pkg/azuredisk/nodeserver.go [hunk 9]
```diff
@@ -543,6 +559,21 @@ func (d *Driver) getDevicePathWithLUN(lunStr string) (string, error) {
 	return newDevicePath, err
 }
 
+func (d *Driver) getDevicePathWithMountPath(mountPath string) (string, error) {
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver.go:562]: would you write a unit test for this?

File: pkg/azuredisk/controllerserver.go [hunk 10]
```diff
@@ -839,6 +845,35 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
 	return generateCSISnapshot(sourceVolumeID, &snapshot)
 }
 
+// GetSourceDiskSize returns: disk size, error
+func (d *Driver) GetSourceDiskSize(resourceGroup, diskName string) (*int32, error) {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:849]: what about merge `GetSourceDiskSize` and `GetSourceDiskSizeHelper` functions as one and write a ut? thanks.

File: pkg/azuredisk/nodeserver.go [hunk 11]
```diff
@@ -216,6 +216,22 @@ func (d *Driver) NodePublishVolume(ctx context.Context, req *csi.NodePublishVolu
 	if err := d.mounter.Mount(source, target, "", mountOptions); err != nil {
 		return nil, status.Errorf(codes.Internal, "Could not mount %q at %q: %v", source, target, err)
 	}
+
+	// if resize is required, resize filesystem
+	if required, ok := req.GetVolumeContext()[resizeRequired]; ok && required == "true" {
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver.go:221]: the mount happens first in NodeStageVolume, I think should move this code to that function, and there is no necessity to change code here if there is already resize in NodeStageVolume

**Review by andyzhangx — COMMENTED** [review]
thanks, with this PR, volume cloning feature should be ready.
And don't forget to `git rebase -i HEAD~7` to squash all commits for this PR.

File: test/e2e/dynamic_provisioning_test.go (hunk 1 above)
Comment (andyzhangx) [reply test/e2e/dynamic_provisioning_test.go:390]: let's try on 1.16 also, pls remove this restriction

File: pkg/azuredisk/controllerserver.go [hunk 12]
```diff
@@ -839,6 +845,35 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
...
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	return d.GetSourceDiskSizeHelper(ctx, resourceGroup, diskName)
+}
+
+// GetSourceDiskSizeHelper is a helper function for GetSourceDiskSize to support recursive search for  and it returns: disk size, error
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:855]: recursive search for sourceDisk?

Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:855]: It is to prevent (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/657#discussion_r552913192).

Comment (nearora-msft) [reply pkg/azuredisk/controllerserver.go:855]: Oh! I meant that the comment seems incomplete. " GetSourceDiskSize to support recursive search for  and it returns". Should it be recursive search for sourceDisk instead?

Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:855]: Oh, thanks for pointing that out. I must have deleted that part in process of editing comments.

File: pkg/azuredisk/nodeserver_test.go [hunk 13]
```diff
@@ -844,3 +844,24 @@ func TestGetDevicePathWithLUN(t *testing.T) {
...
+	d, _ := NewFakeDriver(t)
+	tests := []struct {
+		desc        string
+		req         string
+		expectedErr error
+	}{
+		{
+			desc:        "standard success",
+			req:         "/",
+			expectedErr: nil,
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver_test.go:858]: is there error case?

File: pkg/azuredisk/nodeserver.go [hunk 14]
```diff
@@ -419,6 +434,7 @@ func (d *Driver) NodeExpandVolume(ctx context.Context, req *csi.NodeExpandVolume
 		if len(devicePath) == 0 {
 			return nil, status.Errorf(codes.Internal, "Could not get valid device for mount path: %q", volumePath)
 		}
+		devicePath = output
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver.go:437]: why there is `devicePath = output` here since L433 already did the TrimSpace

File: pkg/azuredisk/nodeserver.go [hunk 15]
```diff
@@ -543,6 +559,25 @@ func (d *Driver) getDevicePathWithLUN(lunStr string) (string, error) {
 	return newDevicePath, err
 }
 
+func (d *Driver) getDevicePathWithMountPath(mountPath string) (string, error) {
+	// currently not supported for mac environment
+	if runtime.GOOS == "darwin" {
```
Comment (andyzhangx) [inline pkg/azuredisk/nodeserver.go:564]: if this is for unit test, we could skip this test in unit test, not in core code

Comment (sunpa93) [reply pkg/azuredisk/nodeserver.go]: Will do

**Comment by nearora-msft** [comment]
> @sunpa93: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-azuredisk-csi-driver-sanity	[ae081e6](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/ae081e6f28ce11b49745dc0da73c93a7a2ec77a9)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/657/pull-azuredisk-csi-driver-sanity/1348806922005909504)	`/test pull-azuredisk-csi-driver-sanity`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=azuredisk-csi-driver&pr=657). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Asunpa93). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues?q=is:issue+is:open) when you hit one in your PR.

This test has been flaky because of this : https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/618#issuecomment-749527145
@andyzhangx should we disable this for the time being?

**Comment by andyzhangx** [comment]
@nearora-msft that reminds me that we should filter out all os disks, `ListVolumes` should not return os disk, that's a bug:
```
I0112 01:42:55.898001    7895 utils.go:84] GRPC call: /csi.v1.Controller/ListVolumes
I0112 01:42:55.898027    7895 utils.go:85] GRPC request: {}
I0112 01:42:55.973836    7895 utils.go:90] GRPC response: {"entries":[{"status":{},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity"}},{"status":{"published_node_ids":["sanity-test-node"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity-test-node_OsDisk_1_0c5cbb6a1bbe4e8e9d400c5ed05a1fa8"}}]}
```

File: pkg/azuredisk/controllerserver.go [hunk 16]
```diff
@@ -846,6 +854,28 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
 	return generateCSISnapshot(sourceVolumeID, &snapshot)
 }
 
+// GetSourceDiskSize recursively searches for the sourceDisk and returns: sourceDisk disk size, error
+func (d *Driver) GetSourceDiskSize(ctx context.Context, resourceGroup, diskName string) (*int32, error) {
+	result, rerr := d.cloud.DisksClient.Get(ctx, resourceGroup, diskName)
+	if rerr != nil {
+		return nil, rerr.Error()
+	}
+
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:863]: remove empty line

**Review by andyzhangx — COMMENTED** [review]
LGTM overall.
Could you squash all commits to one by `git rebase -i HEAD~2` and then force push

File: pkg/azuredisk/controllerserver.go [hunk 17]
```diff
@@ -846,6 +854,28 @@ func (d *Driver) getSnapshotByID(ctx context.Context, resourceGroup, snapshotID,
...
+	if result.DiskProperties == nil {
+		return nil, nil
+	}
+
+	if result.DiskProperties.CreationData != nil && (*result.DiskProperties.CreationData).CreateOption == "Copy" {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:868]: is there a dead loop possibility that `CreateOption == "Copy"`, may define a max depth to avoid this issue.

**Comment by nearora-msft** [comment]
> @nearora-msft that reminds me that we should filter out all os disks(has `_OsDisk_` in disk name), `ListVolumes` should not return os disk, that's a bug:
> 
> ```
> I0112 01:42:55.898001    7895 utils.go:84] GRPC call: /csi.v1.Controller/ListVolumes
> I0112 01:42:55.898027    7895 utils.go:85] GRPC request: {}
> I0112 01:42:55.973836    7895 utils.go:90] GRPC response: {"entries":[{"status":{},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity"}},{"status":{"published_node_ids":["sanity-test-node"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity-test-node_OsDisk_1_0c5cbb6a1bbe4e8e9d400c5ed05a1fa8"}}]}
> ```

Is filtering on the diskName the only option? Isn't there a flag or property that we can use to filter it?

**Comment by andyzhangx** [comment]
> > @nearora-msft that reminds me that we should filter out all os disks(has `_OsDisk_` in disk name), `ListVolumes` should not return os disk, that's a bug:
> > ```
> > I0112 01:42:55.898001    7895 utils.go:84] GRPC call: /csi.v1.Controller/ListVolumes
> > I0112 01:42:55.898027    7895 utils.go:85] GRPC request: {}
> > I0112 01:42:55.973836    7895 utils.go:90] GRPC response: {"entries":[{"status":{},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity"}},{"status":{"published_node_ids":["sanity-test-node"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity-test-node_OsDisk_1_0c5cbb6a1bbe4e8e9d400c5ed05a1fa8"}}]}
> > ```
> 
> Is filtering on the diskName the only option? Isn't there a flag or property that we can use to filter it?

I don't see there is other way since os disk is just a normal disk returned by `ListByResourceGroup`

**Comment by nearora-msft** [comment]
> > > @nearora-msft that reminds me that we should filter out all os disks(has `_OsDisk_` in disk name), `ListVolumes` should not return os disk, that's a bug:
> > > ```
> > > I0112 01:42:55.898001    7895 utils.go:84] GRPC call: /csi.v1.Controller/ListVolumes
> > > I0112 01:42:55.898027    7895 utils.go:85] GRPC request: {}
> > > I0112 01:42:55.973836    7895 utils.go:90] GRPC response: {"entries":[{"status":{},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity"}},{"status":{"published_node_ids":["sanity-test-node"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/azuredisk-csi-driver-test-520f6f1e-5477-11eb-88d4-7ec16ad5bdf3/providers/Microsoft.Compute/disks/sanity-test-node_OsDisk_1_0c5cbb6a1bbe4e8e9d400c5ed05a1fa8"}}]}
> > > ```
> > 
> > 
> > Is filtering on the diskName the only option? Isn't there a flag or property that we can use to filter it?
> 
> I don't see there is other way since os disk is just a normal disk returned by `ListByResourceGroup`

Probably we can use this parameter to check if its an OS disk or not. What do you say? This param is only populated for OS disks as per the docs.
https://docs.microsoft.com/en-us/rest/api/compute/disks/list#hypervgeneration

Created an issue for tracking : https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/678

**Comment by andyzhangx** [comment]
@nearora-msft  that's a little tricky IMO, filter out by diskName should be clear enough

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
