### PR TITLE
test: fix windows output encoding for statefulset and deployment e2e test cases

### LINKED ISSUE #381: fix windows Add-Content command transient error
**What happened**:

may add encoding parameter in the `Add-Content` test:
```
	case "echo 'hello world' >> /mnt/test-1/data && while true; do sleep 1; done":
		return "Add-Content C:\\mnt\\test-1\\data.txt 'hello world'; while (1) { sleep 1 }"
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/380/pull-azuredisk-csi-driver-e2e-windows/1254589218768818176/build-log.txt

```
• Failure [330.245 seconds]
Dynamic Provisioning
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:37
  [single-az]
  /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:40
    should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [It]
    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:263

    Unexpected error:
        <*errors.errorString | 0xc000d40640>: {
            s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00hello world\r\n\"",
        }
        Failed to find "hello world
        hello world
        ", last result: "�������������hello world
        "
    occurred

    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/testsuites.go:467
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

Fixes the output text encoding for the Windows statefulset and deployment e2e test cases by using the Powershell Out-File cmdlet.
Fixes a minor spelling error in test result logging.

**Which issue(s) this PR fixes**:

Fixes #381, #615

Re-enables one of the two test cases (statefulset) for #615. The deployment e2e test is still waiting for fix https://github.com/kubernetes/kubernetes/pull/95456.

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: test/e2e/suite_test.go [hunk 1]
```diff
@@ -251,7 +251,7 @@ func convertToPowershellorCmdCommandIfNecessary(command string) string {
 	case "while true; do echo $(date -u) >> /mnt/test-1/data; sleep 3600; done":
 		return "while (1) { Add-Content -Encoding Ascii C:\\mnt\\test-1\\data.txt $(Get-Date -Format u); sleep 3600 }"
 	case "echo 'hello world' >> /mnt/test-1/data && while true; do sleep 3600; done":
-		return "echo hello world>> C:\\mnt\\test-1\\data.txt&sleep 3600"
+		return "echo 'hello world' | Out-File -Append -FilePath C:\\mnt\\test-1\\data.txt; Get-Content C:\\mnt\\test-1\\data.txt | findstr 'hello world'; Start-Sleep 3600"
```
Comment (andyzhangx) [inline test/e2e/suite_test.go:254]: what is `Get-Content C:\\mnt\\test-1\\data.txt | findstr 'hello world'` for? use `Out-File -Append` fixed this issue, right?

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

File: test/e2e/suite_test.go (hunk 1 above)
Comment (andyzhangx) [reply test/e2e/suite_test.go:254]: I doubt whether this works since there are still failures for test `should create a deployment object, write and read to it, delete the pod and write and read to it again`, will disable this test first.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97439/pull-kubernetes-e2e-azure-disk-windows/1341339223176777728

Comment (edreed) [reply test/e2e/suite_test.go:254]: Hmmm. It looks like a timeout error and not because of the content of the file created by the test. The fix worked when I ran the test in my test cluster and in the automated tests for this PR. I suspect there is another cause for this failure.

> Unexpected error:
        <*errors.errorString | 0xc000891d80>: {
            s: "error waiting for deployment \"azuredisk-volume-tester-5b76m\" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:\"Available\", Status:\"False\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63744233412, loc:(*time.Location)(0x2f9e780)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63744233412, loc:(*time.Location)(0x2f9e780)}}, Reason:\"MinimumReplicasUnavailable\", Message:\"Deployment does not have minimum availability.\"}, v1.DeploymentCondition{Type:\"Progressing\", Status:\"True\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63744233412, loc:(*time.Location)(0x2f9e780)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63744233412, loc:(*time.Location)(0x2f9e780)}}, Reason:\"ReplicaSetUpdated\", Message:\"ReplicaSet \\\"azuredisk-volume-tester-5b76m-5f865796b8\\\" is progressing.\"}}, CollisionCount:(*int32)(nil)}",
        }

Comment (andyzhangx) [reply test/e2e/suite_test.go:254]: looks like this commit fixed the issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/f2c303b9a92395af675b61c88b49884f19c74418
I will continue monitoring the windows e2e test, it's been flacky for a very long time.

Comment (edreed) [reply test/e2e/suite_test.go:254]: Ah, thanks for catching that! :) I missed setting `useCMD` to `false` in my original PR. :(
