### PR TITLE
fix: ListVolumes should be able to return volumes from external rgs as well

### LINKED ISSUE #632: ListVolumes API doesn't list the volumes that are created in an external resource group
**What happened**:
ListVolumes API doesn't list the volumes that are created in a different resource group

**What you expected to happen**:
ListVolumes API should list all the disks that are attached to the nodes in a resource group

**How to reproduce it**:

**Anything else we need to know?**:
With azuredisk csi driver, disks might get created in different resource groups. The current implementation of ListVolumes(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/618) only supports the default case when the disks are created in the current resource group

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sunpa93**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #632 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

File: pkg/azuredisk/controllerserver.go [hunk 1]
```diff
@@ -518,51 +518,70 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
 		}
 	}
 
-	disks, derr := d.cloud.DisksClient.ListByResourceGroup(ctx, d.cloud.ResourceGroup)
-	if derr != nil {
-		return nil, status.Error(codes.Internal, fmt.Sprintf("ListVolumes on rg(%s) failed with error: %v", d.cloud.ResourceGroup, derr.Error()))
+	if d.cloud.KubeClient == nil || d.cloud.KubeClient.CoreV1() == nil || d.cloud.KubeClient.CoreV1().PersistentVolumes() == nil {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:521]: if kubeClient is not set, should return `DisksClient.ListByResourceGroup` result instead of error

File: pkg/azuredisk/controllerserver.go [hunk 2]
```diff
@@ -518,51 +518,70 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			}
+			diskName, err := GetDiskName(diskURI)
+			if err != nil {
+				return nil, status.Errorf(codes.Internal, "could not get disk name from diskURI(%s) with error(%v)", diskURI, err)
+			}
+			resourceGroup, err := GetResourceGroupFromURI(diskURI)
+			if err != nil {
+				return nil, status.Errorf(codes.Internal, "could not get resource group from diskURI(%s) with error(%v)", diskURI, err)
+			}
+			disk, derr := d.cloud.DisksClient.Get(ctx, resourceGroup, diskName)
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:554]: if there are 1K disks, there would be 1K get disk calls, that's too expensive, is it possible to get all resource groups and then `ListByResourceGroup`, that will save get disk calls a lot. Also would you move this code to a standalone function?

Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go]: Thank you for pointing that out.

**Comment by andyzhangx** [comment]
`/ListVolumes` still shows `k8s-master-23068744-0-etcddisk` disk which is actually not a disk PVC in current testing cluster, with this PR, I think it should filter out non disk PVC:

```
I0210 13:01:32.449448       1 utils.go:95] GRPC call: /csi.v1.Controller/ListVolumes
I0210 13:01:32.449477       1 utils.go:96] GRPC request: {}
I0210 13:01:32.478981       1 utils.go:102] GRPC response: {"entries":[{"status":{"published_node_ids":["k8s-master-23068744-0"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-b3c1e461-6b9e-11eb-ae9b-f6d3fab2f43c/providers/Microsoft.Compute/disks/k8s-master-23068744-0-etcddisk"}},{"status":{"published_node_ids":["k8s-agentpool1-23068744-0"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-b3c1e461-6b9e-11eb-ae9b-f6d3fab2f43c/providers/Microsoft.Compute/disks/shared-disk-multiple-pods"}}]}
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/725/pull-azuredisk-csi-driver-e2e-single-az/1359484751718649856/build-log.txt

File: pkg/azuredisk/controllerserver.go [hunk 3]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+	if err != nil {
+		return nil, status.Errorf(codes.Internal, "ListVolumes failed while fetching PersistentVolumes List with error: %v", err.Error())
+	}
+
+	// get all resource groups and put them into a sorted slice
+	rgMap := make(map[string]bool)
+	volSet := make(map[string]bool)
+	numVols := 0
+	for _, pv := range pvList.Items {
+		if pv.Spec.CSI != nil && pv.Spec.CSI.Driver == "disk.csi.azure.com" {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:539]: use `DriverName`  since it's already defined

File: pkg/azuredisk/controllerserver.go [hunk 4]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			diskURI := pv.Spec.CSI.VolumeHandle
+			if err := isValidDiskURI(diskURI); err != nil {
+				return nil, status.Errorf(codes.InvalidArgument, "disk URI(%s) is not valid: %v", diskURI, err)
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:542]: better provide a warning and `continue`

File: pkg/azuredisk/controllerserver.go [hunk 5]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			}
+			rg, err := GetResourceGroupFromURI(diskURI)
+			if err != nil {
+				return nil, status.Errorf(codes.Internal, "could not get resource group from diskURI(%s) with error(%v)", diskURI, err)
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:546]: better provide a warning and continue

File: pkg/azuredisk/controllerserver.go [hunk 6]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
-		maxEntries = int(req.MaxEntries)
+	// loop through each resourceGroup to get disk lists
+	entries := []*csi.ListVolumesResponse_Entry{}
+	numEntries, numVisited, numNotVisited := 0, 0, 0
+	for _, resourceGroup := range resourceGroups {
+		if maxEntries > 0 && numEntries >= maxEntries {
+			numNotVisited++
+			break
+		}
+		derr := d.listVolumesByResourceGroup(ctx, resourceGroup, &entries, start, maxEntries, &numVisited, &numNotVisited, &numEntries, &volSet)
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:576]: should only list volumes which is in `pvList.Items`

File: pkg/azuredisk/controllerserver.go [hunk 7]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+	listVolumesResp := &csi.ListVolumesResponse{
+		Entries:   entries,
+		NextToken: nextTokenString,
+	}
+
+	return listVolumesResp, nil
+}
+
+// listVolumesWithoutKubeClient is a helper function for ListVolumes used for when there is no available kubeclient
+func (d *Driver) listVolumesWithoutKubeClient(ctx context.Context, start, maxEntries int) (*csi.ListVolumesResponse, error) {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:599]: `listVolumesInNodeResourceGroup`

File: pkg/azuredisk/controllerserver.go [hunk 8]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+		return d.listVolumesWithKubeClient(ctx, start, int(req.MaxEntries))
+	}
+	return d.listVolumesWithoutKubeClient(ctx, start, int(req.MaxEntries))
+}
 
-	disks, derr := d.cloud.DisksClient.ListByResourceGroup(ctx, d.cloud.ResourceGroup)
-	if derr != nil {
-		return nil, status.Error(codes.Internal, fmt.Sprintf("ListVolumes on rg(%s) failed with error: %v", d.cloud.ResourceGroup, derr.Error()))
+// listVolumesWithKubeClient is a helper function for ListVolumes used for when there is an available kubeclient
+func (d *Driver) listVolumesWithKubeClient(ctx context.Context, start, maxEntries int) (*csi.ListVolumesResponse, error) {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:528]: `listVolumesInCluster`

File: pkg/azuredisk/controllerserver.go (hunk 6 above)
Comment (andyzhangx) [reply pkg/azuredisk/controllerserver.go:576]: I could still find etcd disks in `ListVolumes` logs, I think that's the root cause: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/725/pull-azuredisk-csi-driver-e2e-single-az/1359837206172143616/build-log.txt

File: pkg/azuredisk/controllerserver.go [hunk 9]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			if _, visited := rgMap[rg]; visited {
+				continue
+			}
+			rgMap[rg] = true
+		}
+		numVols++
 	}
 
-	if start != 0 && start >= len(disks) {
+	if start != 0 && start > numVols {
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:557]: Can we do if start!=0 && start>len(pvList.Items) and move this before the above mentioned loop?

File: pkg/azuredisk/controllerserver.go [hunk 10]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
-		nextTokenString = strconv.Itoa(pageEnd)
-	}
-
-	listVolumesResp := &csi.ListVolumesResponse{
-		Entries:   entries,
-		NextToken: nextTokenString,
-	}
-
-	return listVolumesResp, nil
+	*numVisited, *numNotVisited = *numVisited+i, *numNotVisited-i
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:665]: Changing the values of these variables(numVisited, numNotVisited etc) by reference might lead to synchronization issues if multiple go routines are accessing these at the same time. That might make the values of these variables inconsistent across goroutines.
It would be better to pass these variables into this method by value, change(increment/decrement) the values and then send these to the calling method as return values.

File: pkg/azuredisk/controllerserver.go [hunk 11]
```diff
@@ -517,60 +518,152 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+		disk := disks[i]
+		// if given a set of volumes from KubeClient, only continue if the disk can be found in the set
+		if volSet != nil && (*volSet)[*disk.ID] {
+			continue
+		}
 		// HyperVGeneration property is only setup for os disks. Only the non os disks should be included in the list
-		if d.DiskProperties == nil || d.DiskProperties.HyperVGeneration == "" {
-			if d.ManagedBy != nil {
-				attachedNode, err := vmSet.GetNodeNameByProviderID(*d.ManagedBy)
+		if disk.DiskProperties == nil || disk.DiskProperties.HyperVGeneration == "" {
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:643]: If some of these disks are os disks, they will not be added to the list of entries. So the actual list of entries will be less than the maxEntries even if the len(disks) >= maxEntries. We should keep running the loop as long as there are disks to iterate over and len(entries) < maxEntries.

File: pkg/azuredisk/controllerserver.go (hunk 6 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:576]: > should only list volumes which is in `pvList.Items`

I also thought that this was the cause and have added a `volSet` to keep track of the volumes in `pvList.Items` and only append the disk to the entry if it can be found in `volSet`. However, if etcd disks are still showing up in the results, I think the cause may be something else.

File: pkg/azuredisk/controllerserver.go (hunk 9 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:557]: `pvList.Items` can contain volumes that are not of azure csi driver, so it is inevitable that we loop through each item and confirm that the volume is azure csi disk to get a proper tally of the total volumes `ListVolumes` will return.

File: pkg/azuredisk/controllerserver.go [hunk 12]
```diff
@@ -517,60 +525,167 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
 			return nil, status.Errorf(codes.Aborted, "ListVolumes starting token(%d) can not be negative", start)
 		}
 	}
+	if d.cloud.KubeClient != nil && d.cloud.KubeClient.CoreV1() != nil && d.cloud.KubeClient.CoreV1().PersistentVolumes() != nil {
+		klog.V(2).Infof("List Volumes in Cluster:")
```
[the remark this answers is not in the document]
Comment (andyzhangx) [reply pkg/azuredisk/controllerserver.go:529]: there is no `List Volumes in Cluster` in the logs https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/725/pull-azuredisk-csi-driver-e2e-windows/1362210775858417664/build-log.txt, which means e2e won't List Volumes in Cluster, need to figure out, seems `d.cloud.KubeClient.CoreV1().PersistentVolumes` is nil here

[the remark this answers is not in the document]
Comment (andyzhangx) [reply pkg/azuredisk/controllerserver.go:529]: I have pushed a fix: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/725/commits/ea802d8d85c8582302f9a326bae77d6e7800bd57

[the remark this answers is not in the document]
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go]: I added the log to see if `listVolumesInCluster` was being called at all during the test. This probably explains why there were etcd disks in ListVolumes logs then.

File: pkg/azuredisk/controllerserver.go [hunk 13]
```diff
@@ -517,60 +525,167 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+				klog.Warningf("failed to get resource group from disk uri (%s) with error(%v)", diskURI, err)
+				continue
+			}
+			volSet[diskURI] = true
+			if _, visited := rgMap[rg]; visited {
+				continue
+			}
+			rgMap[rg] = true
+		}
+		numVols++
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:565]: Should we increment this within the if block starting on line 548?

Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:565]: You are right. I don't know how the increment ended up there.

File: pkg/azuredisk/controllerserver.go [hunk 14]
```diff
@@ -517,60 +525,165 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+		}
+		listStatus := d.listVolumesByResourceGroup(ctx, resourceGroup, entries, start-numVisited, maxEntries-len(entries), &volSet)
+		numVisited += listStatus.numVisited
+		if listStatus.err != nil {
+			if status.Code(listStatus.err) == codes.FailedPrecondition {
+				continue
+			}
+			return nil, listStatus.err
+		}
+		entries = listStatus.entries
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:594]: Shouldn't we append the entries here instead of directly setting them. If we set it like this the entries from the previously iterated resource group will get overridden.

Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:594]: entries get passed as a parameter to `listVolumesByResourceGroup` so the returned entries from `listVolumesByResourceGroup` will be always be appended entries including those from previously iterated resource group. So it shouldn't be a problem :)

File: pkg/azuredisk/controllerserver.go [hunk 15]
```diff
@@ -517,60 +525,165 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+	// loop through each resourceGroup to get disk lists
+	entries := []*csi.ListVolumesResponse_Entry{}
+	numVisited := 0
+	isCompleteRun := true
+	for _, resourceGroup := range resourceGroups {
+		if !isCompleteRun || (maxEntries > 0 && len(entries) >= maxEntries) {
+			isCompleteRun = false
+			break
+		}
+		listStatus := d.listVolumesByResourceGroup(ctx, resourceGroup, entries, start-numVisited, maxEntries-len(entries), &volSet)
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:586]: I am not sure if start = start-numVisited will work as expected in all the cases. Let's assume that start = 6 and the number of disks in this resource group is 10. So by the listVolumesByResourceGroup logic, numVisited will be i-start i.e.  10-6 = 4. 

So, in the next iteration start = start- numVisited will be 6-4 = 2, while in reality it should be 0 because we have already moved 6 places ahead in the first iteration.

File: pkg/azuredisk/controllerserver.go (hunk 14 above)
Comment (nearora-msft) [reply pkg/azuredisk/controllerserver.go:594]: Oh ofcourse! My bad.

File: pkg/azuredisk/controllerserver.go [hunk 16]
```diff
@@ -517,60 +525,165 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
-		d := disks[i]
-		nodeList := []string{}
+	listStatus := d.listVolumesByResourceGroup(ctx, d.cloud.ResourceGroup, entries, start, maxEntries, nil)
+	if listStatus.err != nil {
+		return nil, listStatus.err
+	}
+
+	nextTokenString := ""
+	if !listStatus.isCompleteRun {
+		nextTokenString = strconv.Itoa(listStatus.numVisited)
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:620]: I'm not sure if numVisited can work as the nextToken string in all the scenarios. 
Consider the scenario that I mentioned above when start = 6 and there's only 1 rg with 10 disks. The value of numVisited would be 4 and that will also be the next token string. When the call is made to ListVolumes the next time, it will be with startingToken=4  While actually it should be 10.

File: pkg/azuredisk/controllerserver.go [hunk 17]
```diff
@@ -517,60 +525,165 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+				continue
+			}
+			return nil, listStatus.err
+		}
+		entries = listStatus.entries
+		isCompleteRun = isCompleteRun && listStatus.isCompleteRun
+	}
+	nextTokenString := ""
+	if !isCompleteRun {
+		nextTokenString = strconv.Itoa(numVisited)
```
Comment (nearora-msft) [inline pkg/azuredisk/controllerserver.go:599]: I'm not sure if numVisited can work as the nextToken string in all the scenarios.
Consider the scenario that I mentioned above when start = 6 and there's only 1 rg with 10 disks. The value of numVisited would be 4 and that will also be the next token string. When the call is made to ListVolumes the next time, it will be with startingToken=4 While actually it should be 10.

**Comment by andyzhangx** [comment]
at least `List Volumes in Cluster` works now, while etcd disk is still in the result, for every disk, it should exist in cluster disk PV
list, otherwise should filter out:

```
I0218 08:43:30.711123       1 utils.go:95] GRPC call: /csi.v1.Controller/ListVolumes
I0218 08:43:30.711155       1 utils.go:96] GRPC request: {}
I0218 08:43:30.711212       1 controllerserver.go:529] List Volumes in Cluster:
I0218 08:43:30.716771       1 round_trippers.go:445] GET https://10.0.0.1:443/api/v1/persistentvolumes 200 OK in 5 milliseconds
I0218 08:43:30.749000       1 utils.go:102] GRPC response: {"entries":[{"status":{"published_node_ids":["k8s-master-25577820-0"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-c8dc526e-71c3-11eb-9324-be3a24f54b97/providers/Microsoft.Compute/disks/k8s-master-25577820-0-etcddisk"}}]}
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/725/pull-azuredisk-csi-driver-e2e-windows/1362318569785790464/build-log.txt

File: pkg/azuredisk/controllerserver.go (hunk 17 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:599]: It should be `start + numVisited`. Thanks for pointing this out :)

File: pkg/azuredisk/controllerserver.go (hunk 15 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:586]: You are absolutely right. Start token should only be considered until the local iteration of `listVolumeByResourceGroup` finds a starting point. I am really glad that you found this.

**Comment by sunpa93** [comment]
> at least `List Volumes in Cluster` works now, while etcd disk is still in the result, for every disk, it should exist in cluster disk PV
> list, otherwise should filter out:
> 
> ```
> I0218 08:43:30.711123       1 utils.go:95] GRPC call: /csi.v1.Controller/ListVolumes
> I0218 08:43:30.711155       1 utils.go:96] GRPC request: {}
> I0218 08:43:30.711212       1 controllerserver.go:529] List Volumes in Cluster:
> I0218 08:43:30.716771       1 round_trippers.go:445] GET https://10.0.0.1:443/api/v1/persistentvolumes 200 OK in 5 milliseconds
> I0218 08:43:30.749000       1 utils.go:102] GRPC response: {"entries":[{"status":{"published_node_ids":["k8s-master-25577820-0"]},"volume":{"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-c8dc526e-71c3-11eb-9324-be3a24f54b97/providers/Microsoft.Compute/disks/k8s-master-25577820-0-etcddisk"}}]}
> ```
> 
> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/725/pull-azuredisk-csi-driver-e2e-windows/1362318569785790464/build-log.txt

It already filters out any volume that was not found in the pv list (https://github.com/sunpa93/azuredisk-csi-driver/blob/listvolume-fix/pkg/azuredisk/controllerserver.go#L661-L664). Should we try to manually filter out etcd disks either by string comparison or checking disk properties?

File: pkg/azuredisk/controllerserver.go [hunk 18]
```diff
@@ -517,60 +525,170 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+	listVolumesResp := &csi.ListVolumesResponse{
+		Entries:   listStatus.entries,
+		NextToken: nextTokenString,
+	}
+
+	return listVolumesResp, nil
+}
+
+// listVolumesByResourceGroup is a helper function that updates the ListVolumeResponse_Entry slice and returns number of total visited volumes, number of volumes that needs to be visited and an error if found
+func (d *Driver) listVolumesByResourceGroup(ctx context.Context, resourceGroup string, entries []*csi.ListVolumesResponse_Entry, start, maxEntries int, volSet *map[string]bool) listVolumeStatus {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:637]: add comments for func parameters, especially `volSet`, and why use `*map[string]bool` (pointer), map in golang is already pass by reference

File: pkg/azuredisk/controllerserver.go [hunk 19]
```diff
@@ -517,60 +525,170 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			if err := isValidDiskURI(diskURI); err != nil {
+				klog.Warningf("invalid disk uri (%s) with error(%v)", diskURI, err)
+				continue
+			}
+			rg, err := GetResourceGroupFromURI(diskURI)
+			if err != nil {
+				klog.Warningf("failed to get resource group from disk uri (%s) with error(%v)", diskURI, err)
+				continue
+			}
+			volSet[diskURI] = true
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:558]: should convert diskURI to lower case, otherwise there could be duplicated disk URIs

File: pkg/azuredisk/controllerserver.go [hunk 20]
```diff
@@ -517,60 +525,170 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			if _, visited := rgMap[rg]; visited {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:559]: also convert rg to lower case, otherwise there are duplicates

File: pkg/azuredisk/controllerserver.go [hunk 21]
```diff
@@ -517,60 +525,170 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
 			return nil, status.Errorf(codes.Aborted, "ListVolumes starting token(%d) can not be negative", start)
 		}
 	}
+	if d.cloud.KubeClient != nil && d.cloud.KubeClient.CoreV1() != nil && d.cloud.KubeClient.CoreV1().PersistentVolumes() != nil {
+		klog.V(6).Infof("List Volumes in Cluster:")
+		return d.listVolumesInCluster(ctx, start, int(req.MaxEntries))
+	}
+	klog.V(6).Infof("List Volumes in Node Resource Group:")
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:532]: `List Volumes in Node Resource Group: %s`, ...

File: pkg/azuredisk/controllerserver.go [hunk 22]
```diff
@@ -73,6 +74,13 @@ const (
 	sourceDiskSearchMaxDepth = 10
 )
 
+type listVolumeStatus struct {
+	numVisited    int
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:78]: add comments for the fields

File: pkg/azuredisk/controllerserver.go (hunk 18 above)
Comment (andyzhangx) [reply pkg/azuredisk/controllerserver.go:637]: I see, `nil` means it won't filter. In this case, if `volSet` is not nil and is empty, then it should return directly, not necessary to run `DisksClient.ListByResourceGroup`

File: pkg/azuredisk/controllerserver.go [hunk 23]
```diff
@@ -517,60 +525,170 @@ func (d *Driver) ListVolumes(ctx context.Context, req *csi.ListVolumesRequest) (
...
+			volSet[diskURI] = true
+			if _, visited := rgMap[rg]; visited {
+				continue
+			}
+			rgMap[rg] = true
+		}
 	}
 
-	if start != 0 && start >= len(disks) {
+	if start != 0 && start > len(volSet) {
```
Comment (sunpa93) [inline pkg/azuredisk/controllerserver.go:566]: start token refers to an index in a list of all azure disks, including those that may not be csi volumes. This condition compares the start token index to the number of azure csi volumes; therefore it's an invalid comparison.

File: pkg/azuredisk/controllerserver.go (hunk 19 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:558]: I'm sorry but I am not following this. Could you specify?

File: pkg/azuredisk/controllerserver.go (hunk 20 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:559]: I'm sorry but I am not following this. Could you specify?

Comment (andyzhangx) [reply pkg/azuredisk/controllerserver.go:560]: there could be two `diskURI`, which has same rg, while with different case, r.g. `testrg1`, `TESTRG2`

File: pkg/azuredisk/controllerserver.go (hunk 18 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go]: With the current design, `DisksClient.ListByResourceGroup` would need to be called nonetheless to update numVisited because start token refers to an index in a list of all azure disks, not azure csi volumes. But if volSet is not nil and is empty, we should certainly skip the unnecessary loop and return `listVolumeStatus` with updated `numVisited` value.

Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go]: If the start token refers to an index in a list of azure csi disk volumes, we would always have to loop from the start of the disk list returned by `DisksClient.ListByResourceGroup` in `Driver.listVolumesByResourceGroup` in order to find where to actually start adding volume entries. And I am afraid that it would make this process too expensive.

Imagine if there were 1000 azure csi disk volumes and our start token is 900. We have one resource group `rg-1`, and `DisksClient.ListByResourceGroup(ctx, "rg-1")` returns 3000 disks, among which there are 1000 csi volumes. We would then need to iterate from the very start of the list and at worst check 2900 entries to determine where our 900th csi volume is.

On the other hand, if the start token refers to an index in a list of all azure disks, we can start iterating from where the start token points to. Of course, this means that we won't be able to return an error for start token that is too large until we loop through all disks from all resource groups, but the frequency of this happening compared to the abovementioned situation seems to be much lower.

File: pkg/azuredisk/controllerserver.go (hunk 20 above)
Comment (sunpa93) [reply pkg/azuredisk/controllerserver.go:560]: ah, I see what you mean. Thanks for bringing that up 👍

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

File: pkg/azuredisk/mockkubeclient/interface.go [hunk 24]
```diff
@@ -0,0 +1,706 @@
...
+	v11 "k8s.io/client-go/kubernetes/typed/authentication/v1"
+	v1beta11 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"
+	v12 "k8s.io/client-go/kubernetes/typed/authorization/v1"
+	v1beta12 "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"
+	v13 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"
+	v2beta1 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1"
+	v2beta2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2"
+	v14 "k8s.io/client-go/kubernetes/typed/batch/v1"
+	v1beta13 "k8s.io/client-go/kubernetes/typed/batch/v1beta1"
+	v2alpha1 "k8s.io/client-go/kubernetes/typed/batch/v2alpha1"
```
Comment (andyzhangx) [inline pkg/azuredisk/mockkubeclient/interface.go:39]: hi @sunpa93 where did you copy these code from? We have issue upgrading to k8s v0.21.0 lib

Comment (andyzhangx) [reply pkg/azuredisk/mockkubeclient/interface.go:39]: nvm, it's fixed
