### PR TITLE
fix: incorrect disk num discovery on Windows 2019 node

### LINKED ISSUE #3029: Corrupted file system with multiple managed-csi-premium (disk.csi.azure.com) volumes
**What happened**:
When i create multiple Windows pods with a pvc managed-csi-premium the file system is corrupted. It should be empty but some pods have multiple file and folder which referes to something else.

Image

We don't know where these files are coming from but we are sure that the files are not related to our Docker image

The issue can be reproduce manually but we have the same problem within our CICD environment based on Jenkins

**What you expected to happen**:
The pod file system should be empty

**How to reproduce it**:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-1
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-csi-premium
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-2
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-csi-premium
---
apiVersion: "v1"
kind: "Pod"

metadata:
  name: my-windows-pod-1
  namespace: default

spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/windows:10.0.17763.6293
      volumeMounts:
        - name: dynamic-volume
          mountPath: "C:\\\\jenkins"
      workingDir: "C:\\\\jenkins"
      command: [ "powershell.exe", "-Command" ]
      args: [ "while ($true) { Start-Sleep -Seconds 300 }" ]
  volumes:
    - name: dynamic-volume
      persistentVolumeClaim:
        claimName: dynamic-pvc-1
  nodeSelector:
    jenkins/agent: "windows"
  restartPolicy: "Never"
  tolerations:
  - effect: "NoSchedule"
    key: "jenkinspipeline"
    operator: "Equal"
    value: "true"
---
apiVersion: "v1"
kind: "Pod"

metadata:
  name: my-windows-pod-2
  namespace: default

spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/windows:10.0.17763.6293
      volumeMounts:
        - name: dynamic-volume
          mountPath: "C:\\\\jenkins"
      workingDir: "C:\\\\jenkins"
      command: [ "powershell.exe", "-Command" ]
      args: [ "while ($true) { Start-Sleep -Seconds 300 }" ]
  volumes:
    - name: dynamic-volume
      persistentVolumeClaim:
        claimName: dynamic-pvc-2
  nodeSelector:
    jenkins/agent: "windows"
  restartPolicy: "Never"
  tolerations:
  - effect: "NoSchedule"
    key: "jenkinspipeline"
    operator: "Equal"
    value: "true"
```
Running `dir` inside of each pod to see the issue.
The problem occur starting from kubernetes 1.31. The previous versions are working propertly

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v1.31.6
- Kubernetes version (use `kubectl version`):
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.5
- OS (e.g. from /etc/os-release): the version of the nodes or my working station?
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: incorrect disk num discovery on Windows 2019 node

**Which issue(s) this PR fixes**:

Fixes #3029

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
<details>
```
ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -eq 3 })

ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -eq 3 } | Select-Object Index, SCSILogicalUnit, SCSITargetId, SCSIPort, SCSIBus, Model)

PS C:\hpc> ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -Ne 0 } | Select-Object Index, SCSILogicalUnit, SCSITargetId, SCSIPort, SCSIBus, Model)
[
    {
        "Index":  1,
        "SCSILogicalUnit":  1,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  3,
        "SCSILogicalUnit":  3,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  2,
        "SCSILogicalUnit":  2,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  5,
        "SCSILogicalUnit":  4,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  4,
        "SCSILogicalUnit":  5,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  13,
        "SCSILogicalUnit":  6,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  6,
        "SCSILogicalUnit":  7,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  7,
        "SCSILogicalUnit":  8,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  8,
        "SCSILogicalUnit":  9,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  9,
        "SCSILogicalUnit":  10,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  10,
        "SCSILogicalUnit":  11,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  11,
        "SCSILogicalUnit":  12,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  12,
        "SCSILogicalUnit":  13,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  17,
        "SCSILogicalUnit":  14,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  14,
        "SCSILogicalUnit":  15,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  15,
        "SCSILogicalUnit":  0,
        "SCSITargetId":  0,
        "SCSIPort":  3,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  19,
        "SCSILogicalUnit":  16,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  18,
        "SCSILogicalUnit":  17,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  16,
        "SCSILogicalUnit":  1,
        "SCSITargetId":  0,
        "SCSIPort":  3,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
    {
        "Index":  20,
        "SCSILogicalUnit":  18,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    }
]

PS C:\hpc> ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -Ne 0 } | Select-Object Index, SCSILogicalUnit, SCSITargetId, SCSIPort, SCSIBus, Model)
[
    {
        "Index":  1,
        "SCSILogicalUnit":  0,
        "SCSITargetId":  0,
        "SCSIPort":  3,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    }
]



PS C:\hpc> ConvertTo-Json @(Get-Disk | select Number, Location)
[
    {
        "Number":  0,
        "Location":  "PCI Slot 0 : Adapter 0 : Channel 0 : Device 0"
    },
    {
        "Number":  15,
        "Location":  "Integrated : Adapter 3 : Port 0 : Target 0 : LUN 0"
    },
    {
        "Number":  16,
        "Location":  "Integrated : Adapter 3 : Port 0 : Target 0 : LUN 1"
    },
    {
        "Number":  1,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\141\\sandbox.vhdx"
    },
    {
        "Number":  2,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\136\\sandbox.vhdx"
    },
    {
        "Number":  3,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\159\\sandbox.vhdx"
    },
    {
        "Number":  5,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\149\\sandbox.vhdx"
    },
    {
        "Number":  4,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\140\\sandbox.vhdx"
    },
    {
        "Number":  13,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\212\\sandbox.vhdx"
    },
    {
        "Number":  6,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\161\\sandbox.vhdx"
    },
    {
        "Number":  7,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\166\\sandbox.vhdx"
    },
    {
        "Number":  8,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\169\\sandbox.vhdx"
    },
    {
        "Number":  9,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\175\\sandbox.vhdx"
    },
    {
        "Number":  10,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\176\\sandbox.vhdx"
    },
    {
        "Number":  11,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\177\\sandbox.vhdx"
    },
    {
        "Number":  12,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\178\\sandbox.vhdx"
    },
    {
        "Number":  17,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\219\\sandbox.vhdx"
    },
    {
        "Number":  14,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\214\\sandbox.vhdx"
    },
    {
        "Number":  19,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\220\\sandbox.vhdx"
    },
    {
        "Number":  18,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\217\\sandbox.vhdx"
    },
    {
        "Number":  20,
        "Location":  "C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\221\\sandbox.vhdx"
    }
]


PS C:\hpc> Get-Disk -Number 16

Number Friendly Name                                      Serial Number                    HealthStatus         OperationalStatus      Total Size Partition
                                                                                                                                                  Style
------ -------------                                      -------------                    ------------         -----------------      ---------- ----------
16     Msft Virtual Disk                                                                   Healthy              Online                     100 GB RAW


    {
        "Index":  1,
        "SCSILogicalUnit":  1,
        "SCSITargetId":  0,
        "SCSIPort":  4,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },
	
    {
        "Index":  16,
        "SCSILogicalUnit":  1,
        "SCSITargetId":  0,
        "SCSIPort":  3,
        "SCSIBus":  0,
        "Model":  "Microsoft Virtual Disk"
    },

# Gen2 Windows node
I0419 14:02:40.317733     752 utils.go:105] GRPC call: /csi.v1.Node/NodeStageVolume
I0419 14:02:40.317733     752 utils.go:106] GRPC request: {"publish_context":{"LUN":"0"},"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\disk.csi.azure.com\\a63e2d3886284cfbdb45cce97cb66a469f363a5574afdefac52747fc5ca18b42\\globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":7}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-eec2e808-ec85-4cd0-bf30-e80cbaa117be","csi.storage.k8s.io/pvc/name":"persistent-storage-statefulset-azuredisk-win-0","csi.storage.k8s.io/pvc/namespace":"default","requestedsizegib":"100","skuName":"StandardSSD_LRS","storage.kubernetes.io/csiProvisionerIdentity":"1744986261215-3879-disk.csi.azure.com"},"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks131euap_andy-aks131euap_eastus2euap/providers/Microsoft.Compute/disks/pvc-eec2e808-ec85-4cd0-bf30-e80cbaa117be"}
I0419 14:02:49.551773     752 disk.go:100] ListDiskLocations output: [
    {
        "Number":  2,
        "Location":  "Integrated : Bus 0 : Device 63667 : Function 30747 : Adapter 1 : Port 0 : Target 0 : LUN 0",
        "PartitionStyle":  "GPT"
    },
    {
        "Number":  0,
        "Location":  "Integrated : Bus 0 : Device 63667 : Function 30746 : Adapter 0 : Port 0 : Target 0 : LUN 0",
        "PartitionStyle":  "GPT"
    },
    {
        "Number":  1,
        "Location":  "Integrated : Bus 0 : Device 63667 : Function 30746 : Adapter 0 : Port 0 : Target 0 : LUN 1",
        "PartitionStyle":  "MBR"
    }
]
W0419 14:02:49.551773     752 disk.go:139] Got unknown field : Bus=0
W0419 14:02:49.552308     752 disk.go:139] Got unknown field : Device=63667
W0419 14:02:49.552404     752 disk.go:139] Got unknown field : Function=30747
W0419 14:02:49.552404     752 disk.go:139] Got unknown field : Port=0
W0419 14:02:49.552404     752 disk.go:139] Got unknown field : Bus=0
W0419 14:02:49.552404     752 disk.go:139] Got unknown field : Device=63667
W0419 14:02:49.552404     752 disk.go:139] Got unknown field : Function=30746
I0419 14:02:49.552404     752 disk.go:131] skipping adapter 0 disk, number: 0, location: Integrated : Bus 0 : Device 63667 : Function 30746 : Adapter 0 : Port 0 : Target 0 : LUN 0
W0419 14:02:49.552404     752 disk.go:139] Got unknown field : Port=0
I0419 14:02:49.552404     752 disk.go:114] skipping MBR disk, number: 1, location: Integrated : Bus 0 : Device 63667 : Function 30746 : Adapter 0 : Port 0 : Target 0 : LUN 1
I0419 14:02:49.553069     752 nodeserver.go:164] NodeStageVolume: formatting 2 and mounting at \var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\a63e2d3886284cfbdb45cce97cb66a469f363a5574afdefac52747fc5ca18b42\globalmount with mount options([])
I0419 14:02:56.460058     752 disk.go:415] Disk 2 already initialized


```

</details>

**Release note**:
```
fix: incorrect disk num discovery on Windows 2019 node
```

### CODE REVIEW

File: pkg/os/disk/disk.go [hunk 1]
```diff
@@ -127,6 +127,10 @@ func ListDiskLocations() (map[uint32]Location, error) {
 					switch strings.TrimSpace(itemSplit[0]) {
 					case "Adapter":
 						d.Adapter = strings.TrimSpace(itemSplit[1])
+						if d.Adapter == "0" {
```
Comment (andyzhangx) [inline pkg/os/disk/disk.go:130]: @mweibel FYI. since using cim to list disks would break disk recovery in Win 2019, details: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/3029, I would like to use original Get-Disk command to fix this issue (filter out `0` Adapter) to fix this issue. that could also solve the issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2661
