### PR TITLE
fix: disk attach issue when vm in failed status

### LINKED ISSUE #780: use empty PUT operation if disk is in data disk list while vm is in failed state
**What happened**:
There is case that vm is in failed state, disk is already in data disk list while it's actually not attached, should use empty PUT operation to make it work

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: disk attach issue when vm in failed status

**Which issue(s) this PR fixes**:

Fixes #780

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: disk attach issue when vm in failed status
```

### CODE REVIEW

File: pkg/azuredisk/controllerserver.go [hunk 1]
```diff
@@ -416,12 +416,17 @@ func (d *Driver) ControllerPublishVolume(ctx context.Context, req *csi.Controlle
...
 	klog.V(2).Infof("GetDiskLun returned: %v. Initiating attaching volume %q to node %q.", err, diskURI, nodeName)
 
-	lun, err := d.cloud.GetDiskLun(diskName, diskURI, nodeName)
+	lun, vmState, err := d.cloud.GetDiskLun(diskName, diskURI, nodeName)
 	if err == cloudprovider.InstanceNotFound {
 		return nil, status.Error(codes.NotFound, fmt.Sprintf("failed to get azure instance id for node %q (%v)", nodeName, err))
 	}
 
 	if err == nil {
+		if vmState != nil && strings.ToLower(*vmState) == "failed" {
```
Comment (andyzhangx) [inline pkg/azuredisk/controllerserver.go:425]: @MSSedusch this PR is ready for review, let me know if this fixed the issue, thanks.

Comment (MSSedusch) [reply pkg/azuredisk/controllerserver.go:425]: Thanks @andyzhangx. I believe this should fix it. Could you maybe add a log entry if a VM is in a failed state and updated because of it?

Comment (andyzhangx) [reply pkg/azuredisk/controllerserver.go:425]: fixed

**Review by MSSedusch — APPROVED** [review]
lgtm
