### PR TITLE
fix: unit test failure on Windows

### LINKED ISSUE #520: fix unit test failure on Windows
**What happened**:
If some tests could not run on Windows, just skip it, refer to https://github.com/kubernetes-csi/csi-driver-smb/pull/101
```
C:\Users\xiazhang\go\src\sigs.k8s.io\azuredisk-csi-driver>go test -v -race ./pkg/azuredisk/...
=== RUN   TestIoHandler
--- SKIP: TestIoHandler (0.00s)
    azure_common_test.go:127: skip test on GOOS=windows
=== RUN   TestNormalizeKind
--- PASS: TestNormalizeKind (0.00s)
=== RUN   TestNormalizeStorageAccountType
--- PASS: TestNormalizeStorageAccountType (0.00s)
=== RUN   TestNormalizeCachingMode
--- PASS: TestNormalizeCachingMode (0.00s)
=== RUN   TestGetDiskLUN
--- PASS: TestGetDiskLUN (0.00s)
=== RUN   TestStrFirstLetterToUpper
--- PASS: TestStrFirstLetterToUpper (0.00s)
=== RUN   TestGetCloudProvider
W0906 15:50:59.912329   32552 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0906 15:50:59.912329   32552 azure.go:72] Failed to load config from file: C:\k\azure.json
W0906 15:50:59.912329   32552 azure.go:42] get kubeconfig(/tmp/non-exist.json) failed with error: CreateFile /tmp/non-exist.json: The system cannot find the file specified.
E0906 15:50:59.913329   32552 azure.go:72] Failed to load config from file: C:\k\azure.json
W0906 15:50:59.913329   32552 azure.go:42] get kubeconfig(empty-kube-config) failed with error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
W0906 15:50:59.929362   32552 azure_config.go:52] Failed to get cloud-config from secret: failed to get secret azure-cloud-provider: Get https://localhost:8080/api/v1/namespaces/kube-system/secrets/azure-cloud-provider: getting credentials: exec: exec: "foo-command": executable file not found in %PATH%, skip initializing from secret
E0906 15:50:59.929362   32552 azure.go:72] Failed to load config from file: C:\k\azure.json
W0906 15:50:59.930330   32552 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
--- FAIL: TestGetCloudProvider (0.02s)
    azure_test.go:135: desc: [failure] out of cluster, no kubeconfig, no credential file,
         input: "", GetCloudProvider err: Failed to load config from file: C:\k\azure.json, cloud not get azure cloud provider, expectedErr: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
    azure_test.go:135: desc: [failure] out of cluster & in cluster, specify a non-exist kubeconfig, no credential file,
         input: "/tmp/non-exist.json", GetCloudProvider err: Failed to load config from file: C:\k\azure.json, cloud not get azure cloud provider, expectedErr: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
    azure_test.go:135: desc: [failure] out of cluster & in cluster, specify a fake kubeconfig, no credential file,
         input: "fake-kube-config", GetCloudProvider err: Failed to load config from file: C:\k\azure.json, cloud not get azure cloud provider, expectedErr: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
=== RUN   TestIsManagedDisk
--- PASS: TestIsManagedDisk (0.00s)
=== RUN   TestGetDiskName
--- PASS: TestGetDiskName (0.00s)
=== RUN   TestGetSnapshotName
--- PASS: TestGetSnapshotName (0.00s)
=== RUN   TestGetResourceGroupFromURI
--- PASS: TestGetResourceGroupFromURI (0.00s)
=== RUN   TestIsValidDiskURI
--- PASS: TestIsValidDiskURI (0.00s)
=== RUN   TestGetValidDiskName
W0906 15:50:59.932330   32552 azuredisk.go:235] since the maximum volume name length is 80, so it is truncated as ("123456789-123456789-123456789-123456789-123456789.123456789-123456789_1234567890")
--- PASS: TestGetValidDiskName (0.00s)
=== RUN   TestCheckDiskName
--- PASS: TestCheckDiskName (0.00s)
=== RUN   TestGetSourceVolumeID
--- PASS: TestGetSourceVolumeID (0.00s)
=== RUN   TestGetValidCreationData
--- PASS: TestGetValidCreationData (0.00s)
=== RUN   TestIsAvailabilityZone
--- PASS: TestIsAvailabilityZone (0.00s)
=== RUN   TestIsCorruptedDir
--- FAIL: TestIsCorruptedDir (0.00s)
    azuredisk_test.go:555: failed to create curruptedPath: symlink C:\Users\xiazhang\AppData\Local\Temp\csi-mount-test131775607 C:\Users\xiazhang\AppData\Local\Temp\csi-mount-test131775607\curruptedPath: A required privilege is not held by the client.
=== RUN   TestNewDriver
--- PASS: TestNewDriver (0.00s)
=== RUN   TestCheckDiskExists
--- PASS: TestCheckDiskExists (0.00s)
=== RUN   TestCheckDiskCapacity
I0906 15:50:59.936330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.936330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.936330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.936330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.936330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.936330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.936330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestCheckDiskCapacity (0.00s)
=== RUN   TestRun
=== RUN   TestRun/Successful_run
I0906 15:50:59.939332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.939332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.939332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.939332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.939332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.939332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.939332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0906 15:50:59.939332   32552 azuredisk.go:100]
DRIVER INFORMATION:
-------------------
Build Date: N/A
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: N/A
Git Commit: N/A
Go Version: go1.13.14
Platform: windows/amd64
Topology Key: N/A

Streaming logs below:
W0906 15:50:59.939332   32552 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
I0906 15:50:59.942328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.942328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.942328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.942328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.942328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.942328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.942328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0906 15:50:59.949330   32552 server.go:117] Listening for connections on address: &net.TCPAddr{IP:net.IP{0x7f, 0x0, 0x0, 0x1}, Port:51676, Zone:""}
=== RUN   TestRun/Successful_run_with_node_ID_missing
I0906 15:50:59.952330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.952330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.952330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.952330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.952330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.952330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.952330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0906 15:50:59.952330   32552 azuredisk.go:100]
DRIVER INFORMATION:
-------------------
Build Date: N/A
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: N/A
Git Commit: N/A
Go Version: go1.13.14
Platform: windows/amd64
Topology Key: N/A

Streaming logs below:
W0906 15:50:59.952330   32552 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
I0906 15:50:59.953333   32552 azuredisk.go:110] disable UseInstanceMetadata for controller
I0906 15:50:59.954334   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.954334   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.954334   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.954334   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.954334   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.954334   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.954334   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0906 15:50:59.954334   32552 server.go:117] Listening for connections on address: &net.TCPAddr{IP:net.IP{0x7f, 0x0, 0x0, 0x1}, Port:51677, Zone:""}
--- PASS: TestRun (0.02s)
    --- PASS: TestRun/Successful_run (0.01s)
    --- PASS: TestRun/Successful_run_with_node_ID_missing (0.01s)
=== RUN   TestGetCachingMode
--- PASS: TestGetCachingMode (0.00s)
=== RUN   TestGetEntriesAndNextToken
--- PASS: TestGetEntriesAndNextToken (0.00s)
=== RUN   TestCreateVolume
=== RUN   TestCreateVolume/_invalid_
I0906 15:50:59.956333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.956333   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.956333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.956333   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.956333   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.956333   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.956333   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
E0906 15:50:59.956333   32552 controllerserver.go:73] invalid create volume req:
=== RUN   TestCreateVolume/_volume_name_missing
I0906 15:50:59.957333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.957333   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.957333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.957333   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.957333   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.957333   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.957333   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/volume_capabilities_missing
I0906 15:50:59.958332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.958332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.958332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.958332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.958332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.958332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.958332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/require_volume_size_exceed
I0906 15:50:59.960329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.960329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.960329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.960329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.960329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.960329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.960329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/maxshare_parse_error_
I0906 15:50:59.961329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.961329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.961329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.961329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.961329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.961329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.961329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/maxshare_invalid_value_
I0906 15:50:59.963329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.963329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.963329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.963329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.963329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.963329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.963329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/Volume_capability_not_supported_
I0906 15:50:59.965334   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.965334   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.965334   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.965334   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.965334   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.965334   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.965334   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/normalize_storageaccounttype_error_
I0906 15:50:59.966336   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.966336   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.966336   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.966336   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.966336   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.966336   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.966336   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/normalize_cache_mode_error_
I0906 15:50:59.967333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.967333   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.967333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.967333   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.967333   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.967333   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.967333   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/normalize_kind__error_
I0906 15:50:59.968332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.968332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.968332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.968332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.968332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.968332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.968332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/StorageClass_option_error_
I0906 15:50:59.970328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.970328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.970328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.970328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.970328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.970328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.970328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/custom_tags_error_
I0906 15:50:59.971331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.971331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.971331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.971331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.971331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.971331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.971331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/create_managed_disk_error_
I0906 15:50:59.973331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.973331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.973331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.973331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.973331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.973331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.973331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/create_managed_disk_not_found_error_
I0906 15:50:59.974331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.974331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.974331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.974331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.974331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.974331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.974331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateVolume/valid_request_
I0906 15:50:59.975329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.975329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.975329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.975329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.975329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.975329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.975329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestCreateVolume (0.02s)
    --- PASS: TestCreateVolume/_invalid_ (0.00s)
    --- PASS: TestCreateVolume/_volume_name_missing (0.00s)
    --- PASS: TestCreateVolume/volume_capabilities_missing (0.00s)
    --- PASS: TestCreateVolume/require_volume_size_exceed (0.00s)
    --- PASS: TestCreateVolume/maxshare_parse_error_ (0.00s)
    --- PASS: TestCreateVolume/maxshare_invalid_value_ (0.00s)
    --- PASS: TestCreateVolume/Volume_capability_not_supported_ (0.00s)
    --- PASS: TestCreateVolume/normalize_storageaccounttype_error_ (0.00s)
    --- PASS: TestCreateVolume/normalize_cache_mode_error_ (0.00s)
    --- PASS: TestCreateVolume/normalize_kind__error_ (0.00s)
    --- PASS: TestCreateVolume/StorageClass_option_error_ (0.00s)
    --- PASS: TestCreateVolume/custom_tags_error_ (0.00s)
    --- PASS: TestCreateVolume/create_managed_disk_error_ (0.00s)
    --- PASS: TestCreateVolume/create_managed_disk_not_found_error_ (0.00s)
    --- PASS: TestCreateVolume/valid_request_ (0.00s)
=== RUN   TestDeleteVolume
I0906 15:50:59.976329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.977329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.977329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.977329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.977329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.977329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.977329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
E0906 15:50:59.977329   32552 controllerserver.go:335] validateDiskURI(123) in DeleteVolume failed with error: Inavlid DiskURI: 123, correct format: [/subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}]
--- PASS: TestDeleteVolume (0.00s)
=== RUN   TestControllerGetVolume
I0906 15:50:59.979333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.979333   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.979333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.979333   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.979333   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.979333   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.979333   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestControllerGetVolume (0.00s)
=== RUN   TestIsCSISnapshotReady
--- PASS: TestIsCSISnapshotReady (0.00s)
=== RUN   TestGetSnapshotInfo
I0906 15:50:59.980331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.980331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.980331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.980331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.980331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.980331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.980331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestGetSnapshotInfo (0.00s)
=== RUN   TestControllerPublishVolume
I0906 15:50:59.982329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.982329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.982329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.982329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.982329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.982329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.982329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestControllerPublishVolume (0.00s)
=== RUN   TestControllerUnpublishVolume
I0906 15:50:59.983332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.983332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.983332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.983332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.983332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.983332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.983332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestControllerUnpublishVolume (0.00s)
=== RUN   TestControllerGetCapabilities
I0906 15:50:59.984332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.984332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.984332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.984332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.984332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.984332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.985328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestControllerGetCapabilities (0.00s)
=== RUN   TestIsValidVolumeCapabilities
--- PASS: TestIsValidVolumeCapabilities (0.00s)
=== RUN   TestControllerExpandVolume
=== RUN   TestControllerExpandVolume/Volume_ID_missing
I0906 15:50:59.986329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.986329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.986329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.986329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.986329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.986329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.986329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestControllerExpandVolume/Volume_capabilities_missing
I0906 15:50:59.987330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.987330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.987330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.987330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.987330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.987330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.987330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestControllerExpandVolume/Volume_Capacity_range_missing
I0906 15:50:59.988329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.988329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.988329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.988329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.988329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.988329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.988329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestControllerExpandVolume/disk_type_is_not_managedDisk
I0906 15:50:59.989328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.989328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.989328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.989328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.989328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.989328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.989328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestControllerExpandVolume/Disk_URI_not_valid
I0906 15:50:59.990330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.991331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.991331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.991331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.991331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.991331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.991331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestControllerExpandVolume/DiskSize_missing
I0906 15:50:59.992330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.992330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.992330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.992330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.992330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.992330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.992330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestControllerExpandVolume (0.01s)
    --- PASS: TestControllerExpandVolume/Volume_ID_missing (0.00s)
    --- PASS: TestControllerExpandVolume/Volume_capabilities_missing (0.00s)
    --- PASS: TestControllerExpandVolume/Volume_Capacity_range_missing (0.00s)
    --- PASS: TestControllerExpandVolume/disk_type_is_not_managedDisk (0.00s)
    --- PASS: TestControllerExpandVolume/Disk_URI_not_valid (0.00s)
    --- PASS: TestControllerExpandVolume/DiskSize_missing (0.00s)
=== RUN   TestCreateSnapshot
=== RUN   TestCreateSnapshot/Source_volume_ID_missing
I0906 15:50:59.993329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.993329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.993329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.993329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.993329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.993329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.993329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/Snapshot_name_missing
I0906 15:50:59.994330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.994330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.994330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.994330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.994330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.994330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.994330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/Invalid_parameter_option
I0906 15:50:59.995331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.995331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.995331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.995331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.995331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.995331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.995331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/Invalid_volume_ID
I0906 15:50:59.997331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.997331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.997331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.997331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.997331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.997331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.997331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/Invalid_tag_
I0906 15:50:59.998332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.998332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.998332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.998332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.998332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.998332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.998332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/create_snapshot_error_
I0906 15:50:59.999329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:50:59.999329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:50:59.999329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:50:59.999329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:50:59.999329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:50:59.999329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:50:59.999329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/create_snapshot_already_exist_
I0906 15:51:00.000330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.001330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.001330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.001330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.001330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.001330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.001330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/Get_Snapshot_ID_error_
I0906 15:51:00.002330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.002330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.002330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.002330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.002330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.002330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.002330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestCreateSnapshot/valid_request_
I0906 15:51:00.003328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.003328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.003328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.003328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.003328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.003328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.003328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
W0906 15:51:00.042328   32552 azuredisk.go:240] the requested volume name ("testurl/subscriptions/23/providers/Microsoft.Compute/snapshots/snapshot-name") is invalid, so it is regenerated as ("pvc-disk-dynamic-b46f99b9-f015-11ea-ab1f-00155de1a4f6")
--- PASS: TestCreateSnapshot (0.05s)
    --- PASS: TestCreateSnapshot/Source_volume_ID_missing (0.00s)
    --- PASS: TestCreateSnapshot/Snapshot_name_missing (0.00s)
    --- PASS: TestCreateSnapshot/Invalid_parameter_option (0.00s)
    --- PASS: TestCreateSnapshot/Invalid_volume_ID (0.00s)
    --- PASS: TestCreateSnapshot/Invalid_tag_ (0.00s)
    --- PASS: TestCreateSnapshot/create_snapshot_error_ (0.00s)
    --- PASS: TestCreateSnapshot/create_snapshot_already_exist_ (0.00s)
    --- PASS: TestCreateSnapshot/Get_Snapshot_ID_error_ (0.00s)
    --- PASS: TestCreateSnapshot/valid_request_ (0.04s)
=== RUN   TestDeleteSnapshot
=== RUN   TestDeleteSnapshot/Snapshot_ID_missing
I0906 15:51:00.043330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.044330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.044330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.044330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.044330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.044330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.044330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestDeleteSnapshot/Snapshot_ID_invalid
I0906 15:51:00.045330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.045330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.045330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.045330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.045330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.045330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.045330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestDeleteSnapshot/delete_Snapshot_error
I0906 15:51:00.046329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.046329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.046329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.046329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.046329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.046329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.046329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestDeleteSnapshot/Valid_delete_Snapshot_
I0906 15:51:00.048328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.048328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.048328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.048328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.048328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.048328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.048328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestDeleteSnapshot (0.01s)
    --- PASS: TestDeleteSnapshot/Snapshot_ID_missing (0.00s)
    --- PASS: TestDeleteSnapshot/Snapshot_ID_invalid (0.00s)
    --- PASS: TestDeleteSnapshot/delete_Snapshot_error (0.00s)
    --- PASS: TestDeleteSnapshot/Valid_delete_Snapshot_ (0.00s)
=== RUN   TestGenerateCSISnapshot
=== RUN   TestGenerateCSISnapshot/snap_shot_property_not_exist
I0906 15:51:00.049330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.049330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.049330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.049330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.049330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.049330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.049330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestGenerateCSISnapshot/diskSizeGB_of_snapshot_property_is_nil
I0906 15:51:00.050328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.050328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.050328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.050328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.050328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.050328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.050328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestGenerateCSISnapshot/valid_request
--- PASS: TestGenerateCSISnapshot (0.00s)
    --- PASS: TestGenerateCSISnapshot/snap_shot_property_not_exist (0.00s)
    --- PASS: TestGenerateCSISnapshot/diskSizeGB_of_snapshot_property_is_nil (0.00s)
    --- PASS: TestGenerateCSISnapshot/valid_request (0.00s)
=== RUN   TestGetSnapshotByID
=== RUN   TestGetSnapshotByID/snapshotID_not_valid
I0906 15:51:00.053329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.053329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.053329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.053329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.053329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.053329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.053329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestGetSnapshotByID/snapshot_get_error
I0906 15:51:00.055331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.055331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.055331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.055331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.055331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.055331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.055331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestGetSnapshotByID (0.00s)
    --- PASS: TestGetSnapshotByID/snapshotID_not_valid (0.00s)
    --- PASS: TestGetSnapshotByID/snapshot_get_error (0.00s)
=== RUN   TestListSnapshots
=== RUN   TestListSnapshots/snapshotID_not_valid
I0906 15:51:00.056330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.056330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.056330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.056330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.056330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.056330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.056330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestListSnapshots/valid_List
I0906 15:51:00.058328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.058328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.058328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.058328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.058328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.058328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.058328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestListSnapshots/List_resource_error
I0906 15:51:00.060329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.060329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.060329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.060329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.060329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.060329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.060329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestListSnapshots/snapshot_property_nil
I0906 15:51:00.061328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.061328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.061328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.061328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.061328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.061328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.061328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestListSnapshots (0.01s)
    --- PASS: TestListSnapshots/snapshotID_not_valid (0.00s)
    --- PASS: TestListSnapshots/valid_List (0.00s)
    --- PASS: TestListSnapshots/List_resource_error (0.00s)
    --- PASS: TestListSnapshots/snapshot_property_nil (0.00s)
=== RUN   TestGetCapacity
I0906 15:51:00.062330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.062330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.062330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.062330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.062330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.062330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.062330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestGetCapacity (0.00s)
=== RUN   TestListVolumes
I0906 15:51:00.063330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.064333   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.064333   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.064333   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.064333   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.064333   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.064333   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestListVolumes (0.00s)
=== RUN   TestValidateVolumeCapabilities
=== RUN   TestValidateVolumeCapabilities/Volume_ID_missing_
I0906 15:51:00.065329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.065329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.065329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.065329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.065329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.065329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.065329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestValidateVolumeCapabilities/Volume_capabilities_missing_
I0906 15:51:00.066328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.066328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.066328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.066328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.066328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.066328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.066328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestValidateVolumeCapabilities/check_disk_err_
I0906 15:51:00.068329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.068329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.068329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.068329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.068329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.068329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.068329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestValidateVolumeCapabilities/invalid_req_
I0906 15:51:00.069329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.069329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.069329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.069329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.069329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.069329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.069329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
=== RUN   TestValidateVolumeCapabilities/valid_req_
I0906 15:51:00.070328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.070328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.070328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.070328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.070328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.070328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.070328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestValidateVolumeCapabilities (0.01s)
    --- PASS: TestValidateVolumeCapabilities/Volume_ID_missing_ (0.00s)
    --- PASS: TestValidateVolumeCapabilities/Volume_capabilities_missing_ (0.00s)
    --- PASS: TestValidateVolumeCapabilities/check_disk_err_ (0.00s)
    --- PASS: TestValidateVolumeCapabilities/invalid_req_ (0.00s)
    --- PASS: TestValidateVolumeCapabilities/valid_req_ (0.00s)
=== RUN   TestPickAvailabilityZone
=== RUN   TestPickAvailabilityZone/requirement_missing_
=== RUN   TestPickAvailabilityZone/valid_get_preferred
=== RUN   TestPickAvailabilityZone/valid_get_requisite
=== RUN   TestPickAvailabilityZone/empty_request_
--- PASS: TestPickAvailabilityZone (0.00s)
    --- PASS: TestPickAvailabilityZone/requirement_missing_ (0.00s)
    --- PASS: TestPickAvailabilityZone/valid_get_preferred (0.00s)
    --- PASS: TestPickAvailabilityZone/valid_get_requisite (0.00s)
    --- PASS: TestPickAvailabilityZone/empty_request_ (0.00s)
=== RUN   TestNewFakeDriver
I0906 15:51:00.073329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.073329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.073329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.073329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.073329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.073329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.073329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestNewFakeDriver (0.00s)
=== RUN   TestMount
I0906 15:51:00.074331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.074331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.074331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.074331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.074331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.074331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.074331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestMount (0.00s)
=== RUN   TestMountSensitive
I0906 15:51:00.075332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.075332   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.075332   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.075332   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.075332   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.075332   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.075332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestMountSensitive (0.00s)
=== RUN   TestIsLikelyNotMountPoint
I0906 15:51:00.077330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.077330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.077330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.077330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.077330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.077330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.077330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestIsLikelyNotMountPoint (0.00s)
=== RUN   TestGetPluginInfo
I0906 15:51:00.078329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.078329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.078329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.078329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.078329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.078329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.078329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0906 15:51:00.079329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.079329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.079329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.079329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.079329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.079329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.079329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0906 15:51:00.080329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.080329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.080329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.080329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.080329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.080329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.081332   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestGetPluginInfo (0.00s)
=== RUN   TestProbe
I0906 15:51:00.082329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.082329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.082329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.082329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.082329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.082329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.082329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestProbe (0.00s)
=== RUN   TestGetPluginCapabilities
I0906 15:51:00.083331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.083331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.083331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.083331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.083331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.083331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.083331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestGetPluginCapabilities (0.00s)
=== RUN   TestNodeGetCapabilities
I0906 15:51:00.085329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.085329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.085329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.085329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.085329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.085329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.085329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestNodeGetCapabilities (0.00s)
=== RUN   TestGetFStype
--- PASS: TestGetFStype (0.00s)
=== RUN   TestGetMaxDataDiskCount
--- PASS: TestGetMaxDataDiskCount (0.00s)
=== RUN   TestEnsureMountPoint
I0906 15:51:00.088329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.088329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.088329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.088329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.088329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.088329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.088329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
IsCorruptedDir(./error_is_likely_target) returned with error: <nil>--- FAIL: TestEnsureMountPoint (0.00s)
    nodeserver_test.go:178: desc: [Error] Not a directory
         actualErr: (<nil>), expectedErr: (mkdir ./azure.go: The system cannot find the path specified.)
=== RUN   TestNodeGetVolumeStats
I0906 15:51:00.090328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.090328   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.090328   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.090328   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.090328   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.090328   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.090328   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- PASS: TestNodeGetVolumeStats (0.00s)
=== RUN   TestNodeStageVolume
--- SKIP: TestNodeStageVolume (0.00s)
    nodeserver_test.go:237: skip test on GOOS=windows
=== RUN   TestNodeUnstageVolume
I0906 15:51:00.093329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.093329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.093329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.093329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.093329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.093329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.093329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- FAIL: TestNodeUnstageVolume (0.00s)
    nodeserver_test.go:372: desc: [Error] CleanupMountPoint error mocked by IsLikelyNotMountPoint
         actualErr: (<nil>), expectedErr: (rpc error: code = Internal desc = failed to unmount staging target "./error_is_likely_target": fake IsLikelyNotMountPoint: fake error)
=== RUN   TestNodePublishVolume
I0906 15:51:00.095330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.095330   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.095330   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.095330   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.095330   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.095330   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.095330   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- FAIL: TestNodePublishVolume (0.00s)
    nodeserver_test.go:495: desc: [Error] Not a directory
         actualErr: (rpc error: code = Internal desc = Target path could not be prepared: could not cast to csi proxy class), expectedErr: (rpc error: code = Internal desc = Could not mount target "./azure.go": mkdir ./azure.go: not a directory)
    nodeserver_test.go:495: desc: [Error] Lun not provided
         actualErr: (rpc error: code = Internal desc = Target path could not be prepared: could not cast to csi proxy class), expectedErr: (rpc error: code = InvalidArgument desc = lun not provided)
    nodeserver_test.go:495: desc: [Error] Lun not valid
         actualErr: (rpc error: code = Internal desc = Target path could not be prepared: could not cast to csi proxy class), expectedErr: (rpc error: code = Internal desc = Failed to find device path with lun /dev/01. cannot parse deviceInfo: /dev/01)
    nodeserver_test.go:495: desc: [Error] Mount error mocked by Mount
         actualErr: (rpc error: code = Internal desc = Target path could not be prepared: could not cast to csi proxy class), expectedErr: (rpc error: code = Internal desc = Could not mount "./error_mount_source" at "./target_test": fake Mount: source error)
    nodeserver_test.go:495: desc: [Success] Valid request already mounted
         actualErr: (rpc error: code = Internal desc = Target path could not be prepared: could not cast to csi proxy class), expectedErr: (<nil>)
    nodeserver_test.go:495: desc: [Success] Valid request
         actualErr: (rpc error: code = Internal desc = Target path could not be prepared: could not cast to csi proxy class), expectedErr: (<nil>)
=== RUN   TestNodeUnpublishVolume
I0906 15:51:00.098329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.098329   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.098329   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.098329   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.098329   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.098329   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.098329   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- FAIL: TestNodeUnpublishVolume (0.00s)
    nodeserver_test.go:549: desc: [Error] Unmount error mocked by IsLikelyNotMountPoint
         actualErr: (<nil>), expectedErr: (rpc error: code = Internal desc = failed to unmount target "./error_is_likely_target": fake IsLikelyNotMountPoint: fake error)
=== RUN   TestNodeExpandVolume
I0906 15:51:00.100331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.100331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.100331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.100331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.100331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.100331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.100331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- FAIL: TestNodeExpandVolume (0.01s)
    nodeserver_test.go:587: desc: cound not find path
         actualErr: (rpc error: code = Internal desc = Could not determine device path: executable file not found in %PATH%), expectedErr: (rpc error: code = Internal desc = Could not determine device path: exit status 1)
=== RUN   TestGetBlockSizeBytes
I0906 15:51:00.112331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.112331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.112331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.112331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.112331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.112331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.112331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- FAIL: TestGetBlockSizeBytes (0.01s)
    nodeserver_test.go:614: desc: no exist path
         actualErr: (error when getting size of block volume at path testpath: output: , err: executable file not found in %PATH%), expectedErr: (error when getting size of block volume at path testpath: output: , err: exit status 1)
    nodeserver_test.go:614: desc: invalid path
         actualErr: (error when getting size of block volume at path ./test: output: , err: executable file not found in %PATH%), expectedErr: (error when getting size of block volume at path ./test: output: , err: exit status 1)
=== RUN   TestEnsureBlockTargetFile
I0906 15:51:00.126331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0906 15:51:00.126331   32552 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0906 15:51:00.126331   32552 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0906 15:51:00.126331   32552 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0906 15:51:00.126331   32552 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0906 15:51:00.126331   32552 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0906 15:51:00.126331   32552 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
--- FAIL: TestEnsureBlockTargetFile (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1e7d8c5]

goroutine 638 [running]:
testing.tRunner.func1(0xc0002ce800)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0x20ffd80, 0x33a7170)
        c:/go/src/runtime/panic.go:679 +0x1c0
sigs.k8s.io/azuredisk-csi-driver/pkg/mounter.(*CSIProxyMounter).ExistsPath(0xc000422180, 0x2319e75, 0x1, 0x0, 0x6353f8, 0x5b9d04)
        C:/Users/xiazhang/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/mounter/safe_mounter_windows.go:168 +0x1a5
sigs.k8s.io/azuredisk-csi-driver/pkg/mounter.(*CSIProxyMounter).IsLikelyNotMountPoint(0xc000422180, 0x2319e75, 0x1, 0xc0006eeb50, 0xc0006eeb10, 0x33e9408)
        C:/Users/xiazhang/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/mounter/safe_mounter_windows.go:106 +0x72
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).ensureMountPoint(0xc0009cc240, 0x2319e75, 0x1, 0x1, 0xc000619270)
        C:/Users/xiazhang/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/nodeserver.go:429 +0xc1
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).ensureBlockTargetFile(0xc0009cc240, 0x2319e75, 0x6, 0x0, 0xc0004651e0)
        C:/Users/xiazhang/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/nodeserver.go:515 +0x97
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.TestEnsureBlockTargetFile(0xc0002ce800)
        C:/Users/xiazhang/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/nodeserver_test.go:644 +0x279
testing.tRunner(0xc0002ce800, 0x23dac48)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk  2.324s
FAIL
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc @mayankshah1607

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
/kind test
/kind cleanup

**What this PR does / why we need it**:
Fix unit test failures on Windows

**Which issue(s) this PR fixes**:

Fixes #520

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by mayankshah1607** [comment]
@andyzhangx PTAL! :)
Shall we also enable the Windows worflow? Looks like it is currently not running - https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/.github/workflows/window

File: pkg/azuredisk/azuredisk_test.go [hunk 1]
```diff
@@ -544,6 +544,7 @@ func TestIsAvailabilityZone(t *testing.T) {
 }
 
 func TestIsCorruptedDir(t *testing.T) {
+	skipTestsIfWindows(t)
```
Comment (andyzhangx) [inline pkg/azuredisk/azuredisk_test.go:547]: do you know how to configure this test in admin mode, actually test unit test could pass in admin mode on Windows:
```
>go test -run TestIsCorruptedDir
--- FAIL: TestIsCorruptedDir (0.00s)
    azuredisk_test.go:555: failed to create curruptedPath: symlink C:\Users\xiazhang\AppData\Local\Temp\csi-mount-test769943179 C:\Users\xiazhang\AppData\Local\Temp\csi-mount-test769943179\curruptedPath: A required privilege is not held by the client.
```

Comment (andyzhangx) [reply pkg/azuredisk/azuredisk_test.go:547]: could be some setting in windows.yaml config:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/.github/workflows/window#L28

**Comment by andyzhangx** [comment]
> @andyzhangx PTAL! :)
> Shall we also enable the Windows workflow? Looks like it is currently not running - https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/.github/workflows/window

waiting for this PR: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/521

File: pkg/azuredisk/azuredisk_test.go (hunk 1 above)
Comment (andyzhangx) [reply pkg/azuredisk/azuredisk_test.go:547]: there is a possibility to use following runas command to solve this issue, while it still prompt password, need to figure it out later:
https://www.tenforums.com/general-support/111929-how-use-runas-without-password-prompt.html

```
C:\Users\xiazhang\go\src\sigs.k8s.io\azuredisk-csi-driver\pkg\azuredisk>runas /user:Administrator "go test -run TestIsCorruptedDir"
Enter the password for Administrator:
```

Comment (mayankshah1607) [reply pkg/azuredisk/azuredisk_test.go:547]: @andyzhangx Just went through this issue thread - https://github.com/golang/dep/issues/773
Seems like its an issue from the `os.Symlink` client library that's preventing the machine from creating Symlinks. 
I tried running the test as administrator from Command promt and it seemed to PASS.

WDYT about skipping this test for now until we figure out a way to run as admin from the workflow?

Comment (andyzhangx) [reply pkg/azuredisk/azuredisk_test.go:547]: ok

File: pkg/azuredisk/azure_test.go [hunk 2]
```diff
@@ -21,10 +21,18 @@ import (
...
 )
 
+func skipTestsIfWindows(t *testing.T) {
+	if runtime.GOOS == "windows" {
+		t.Skip("Skipping tests on Windows")
+	}
+}
+
 func TestGetCloudProvider(t *testing.T) {
+	skipTestsIfWindows(t)
```
Comment (andyzhangx) [inline pkg/azuredisk/azure_test.go:35]: rename as `skipIfTestingOnWindows`

**Review by andyzhangx — COMMENTED** [review]
pls also add a new line `go test -v -race ./pkg/azuredisk/...` under
or set as `go test -v -race ./pkg/...`


https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/dd9ecf725425aa3c1af77dc106c81f290e063a2e/.github/workflows/windows.yml#L28

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
